name: Run Python script

on: 
  schedule:
    # 日本時間の毎朝7時（UTCの毎日22時）に実行
    - cron: '0 22 * * *'
  workflow_dispatch:
    # 手動実行を許可

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script for server 1
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_pNouns }}
      run: python main.py
    - name: Run script for server 2
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_Test }}
      run: python main.py
